server:
  port: 8090
  error:
    include-message: always

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true


spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  application:
    name: access-control-service
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  jmx:
    enabled: false
  datasource:
    url: jdbc:mysql://localhost:3306/access_control?allowPublicKeyRetrieval=true&sslMode=DISABLED
    username: root
    password: root
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/auth/realms/application-users
          jwk-set-uri: http://localhost:8180/auth/realms/application-users/protocol/openid-connect/certs

keycloak:
  realm: application-users
  auth-server-url: http://localhost:8180/auth
  resource: admin-cli
  bearer-only: true
  credentials:
    secret: gv7zpYNOH51UUZZoBojyjMwsDtAk8LzT
  security-constraints:
    - auth-roles: user
    - security-collections:
        - name: user
        - patterns: /user/*